["protostar.config"]
protostar_version = "0.1.0"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
space = [
    "./contracts/core/space.cairo",
]
dust = [
    "./contracts/core/dust.cairo",
]
rand = [
    "./contracts/core/rand.cairo",
]
static_ship = [
    "./contracts/ships/static_ship.cairo",
]
