name: Formatting

on: push

jobs:
  cairo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          pip install cairo-lang
      - name: Check files formatting
        run: cairo-format -c contracts/**/*.cairo
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          pip install black
      - name: Check files formatting
        run: black --check src tests
