name: Test

on:
  pull_request: ~

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Build binary
        run: |
          poetry run poe build
      - name: Run tests
        run: |
          poetry run pytest src
  exercises-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.12
      - name: Install protostar
        run: |
          curl -L https://raw.githubusercontent.com/software-mansion/protostar/master/install.sh | bash
      - name: Run exercise tests
        run: |
          chmod +x ./scripts/patch_and_test_exercises.sh
          ./scripts/patch_and_test_exercises.sh
        shell: bash
